from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.file_path = None  # 添加file_path屬性，初始化為None
        self.limit = 5  # 添加file_path屬性，初始化為None
        self.delimiter = '\t'  # TSV文件使用tab作為分隔符
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        MainWindow.resize(800, 600)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.TitleLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.TitleLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.TitleLabel.setObjectName("TitleLabel")
        self.gridLayout.addWidget(self.TitleLabel, 3, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(parent=self.centralwidget)
        self.tableView.setLineWidth(1)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setCascadingSectionResizes(True)
        self.gridLayout.addWidget(self.tableView, 0, 0, 1, 3)
        self.SubmitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SubmitButton.setObjectName("SubmitButton")
        self.gridLayout.addWidget(self.SubmitButton, 3, 2, 1, 1)
        self.PreviousButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.PreviousButton.setObjectName("PreviousButton")
        self.gridLayout.addWidget(self.PreviousButton, 1, 0, 1, 1)
        self.NextButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.NextButton.setObjectName("NextButton")
        self.gridLayout.addWidget(self.NextButton, 1, 2, 1, 1)
        self.ClearButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ClearButton.setObjectName("ClearButton")
        self.gridLayout.addWidget(self.ClearButton, 2, 2, 1, 1)
        self.SelectButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SelectButton.setObjectName("SelectButton")
        self.gridLayout.addWidget(self.SelectButton, 2, 1, 1, 1)
        self.InputTextBox = QtWidgets.QTextEdit(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.InputTextBox.sizePolicy().hasHeightForWidth())
        self.InputTextBox.setSizePolicy(sizePolicy)
        self.InputTextBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.InputTextBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.InputTextBox.setObjectName("InputTextBox")
        self.gridLayout.addWidget(self.InputTextBox, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NowPageLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.NowPageLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.NowPageLabel.setObjectName("NowPageLabel")
        self.horizontalLayout.addWidget(self.NowPageLabel)
        self.TotalPageLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.TotalPageLabel.setObjectName("TotalPageLabel")
        self.horizontalLayout.addWidget(self.TotalPageLabel)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TitleLabel.setText(_translate("MainWindow", "Limit:"))
        self.SubmitButton.setText(_translate("MainWindow", "Submit"))
        self.PreviousButton.setText(_translate("MainWindow", "<"))
        self.NextButton.setText(_translate("MainWindow", ">"))
        self.ClearButton.setText(_translate("MainWindow", "Clear"))
        self.SelectButton.setText(_translate("MainWindow", "Load"))
        self.NowPageLabel.setText(_translate("MainWindow", "NowPage"))
        self.TotalPageLabel.setText(_translate("MainWindow", "/TotalPageLabel"))